[project]
name = "temp-sensor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "orjson>=3.10.18",
    "pip>=25.1.1",
    "pychromecast>=14.0.7",
    "ruff>=0.11.11",
    "setuptools>=80.8.0",
    "wheel>=0.45.1",
]
